feat(breaking-changes): adds template for breaking changes doc
open-turo/standards-terraform pull request #11
Opened 2023-07-04 16:25 UTC by yohanb

### Description

Adding a template for breaking change markdown document.

This will help engineers to understand what needs to be included for a breaking change document and thereby providing a consistency across all the breaking change documentation

Changes

feat(breaking-changes): adds template for breaking changes doc
🚀 PR created with [fotingo](https://github.com/tagoro9/fotingo)

2023-07-04 16:27 UTC, yohanb commented on templates/breaking-changes-doc-template.md
> +# Upgrade from v[PREVIOUS].x to v[CURRENT].x
We've used this style of template variable elsewhere so I would suggest to do the same here

```suggestion
# Upgrade from v**PREVIOUS**.x to v**CURRENT**.x
```

2023-07-04 23:45 UTC, greenkiwi approved these changes

2023-07-04 23:46 UTC, greenkiwi requested changes
I don't think that there are breaking changes here. Let's rebase/squash. 

This is probably a fix, since it is just clarifying the existing standard.

2023-07-05 16:07 UTC, gopkri24 commented
> I don't think that there are breaking changes here. Let's rebase/squash.
> 
> This is probably a fix, since it is just clarifying the existing standard.
> 
> See: https://open-turo.github.io/standards-terraform/changes/

Updated it to `fix`

2023-07-05 17:24 UTC, merged